services:
  postgres:
    container_name: postgres
    image: 'postgres:15'
    restart: always
    environment:
      # Mapiramo tvoje nazive iz .env na nazive koje Postgres image prepoznaje
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      # Ovde takođe koristimo varijablu za korisnika kako bi healthcheck prošao
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - ./pgsql:/var/lib/postgresql/data
      - './init-db.sh:/docker-entrypoint-initdb.d/init-db.sh'
    env_file:
      - .env
    networks:
      - default

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3000:80"
    # Napomena: 'links' je zastarela opcija, 'depends_on' je sasvim dovoljan
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default

networks:
  default:
    driver: bridge

